Lint/EmptyWhen:
  Exclude:
    - 'Rules'
    - 'lib/dmark_translators/common.rb'
    - 'lib/dmark_translators/latex.rb'

Naming/PredicateName:
  Exclude:
    - 'spec/**/*'
    - 'lib/dmark_translators/common.rb'

Security/Eval:
  Exclude:
    - 'Checks'
    - 'lib/dmark_translators/html.rb'
    - 'lib/dmark_translators/latex.rb'

Style/IfInsideElse:
  Exclude:
    - 'lib/dmark_translators/common.rb'

Style/RegexpLiteral:
  Exclude:
    - 'Checks'
