language: ruby
branches:
  only:
    - "master"
    - "/^release-/"
rvm:
  - 2.4.0
cache: bundler
sudo: false
git:
  depth: 10
before_install:
  - gem install bundler
  - bundle config github.https true
addons:
  apt:
    packages:
    - libaspell-dev
    - aspell-en
