base_url: http://nanoc.stoneship.org/
data_sources:
  - type: filesystem_compact
    items_root:   '/'
    layouts_root: '/'
deploy:
  default:
    dst:     "ectype:sites/nanoc/public"
    options: [ '-gpPrvz', '--exclude=".hg"', '--delete-after' ]
page_size: 5
enable_ramalytics: false
