enable_output_diff: true

prune:
  auto_prune: true

data_sources:
  -
    type:         filesystem_unified
    items_root:   /
    layouts_root: /
  -
    type:         cli
    items_root:   /docs/reference/commands/
  -
    type:         yard
    items_root:   /docs/reference/
  -
    type:         static
    items_root:   /static/
  -
    type:         ssg_comparison
    items_root:   /about/ssgs/

base_url: http://nanoc.ws

deploy:
  public:
    kind: s3
    dst: "s3://nanoc.ws/"
  staging:
    kind: s3
    dst: "s3://staging.nanoc.ws/"
