base_url: http://nanoc.stoneship.org/
data_sources:
  - type: filesystem_unified
    items_root:   '/'
    layouts_root: '/'
deploy:
  default:
    dst:     "ectype:sites/nanoc/public"
    options: [ '-gpPrtvz', '--exclude=".hg"' ]
page_size: 5
enable_ramalytics: false
