enable_output_diff: true

prune:
  auto_prune: true

data_sources:
  -
    type:         filesystem_unified
    items_root:   /
    layouts_root: /
  -
    type:         static
    items_root:   /static/

base_url: http://nanoc.stoneship.org/

deploy:
  default:
    kind: rsync
    dst: "ectype:sites/nanoc/public"
  staging:
    kind: rsync
    dst: "ectype:sites/nanoc-staging/public"
    options: [ '-aP', '--delete-after' ]
